_partial_: false
model: ???
is_multi_target: false
internal_batch_size: 64
weight_attributions: false
module: torchxai.explainers._perturbation.feature_ablation.FeatureAblationExplainer
_target_: atria_insights.registry.registry_groups.ExplainerBuilder
