_partial_: false
model: ???
is_multi_target: false
internal_batch_size: 1
n_samples: 100
alpha: 0.01
weight_attributions: true
module: torchxai.explainers._perturbation.lime.LimeExplainer
_target_: atria_insights.registry.registry_groups.ExplainerBuilder
