_target_: insightx.metrics.torchxai_metric.TorchXAIMetric
_partial_: true
metric_func:
  _target_: torchxai.metrics.complexity.complexity_sundararajan.complexity_sundararajan
  _partial_: true
  eps: 1.0e-05
  normalize_attribution: true
  is_multi_target: false
  return_dict: false
output_transform:
  path: insightx.metrics.torchxai_metric.default_output_transform
  _target_: hydra_zen.funcs.get_obj
device: cpu
progress_bar: null
attached_name: null
