_target_: insightx.metrics.torchxai_metric.TorchXAIMetric
_partial_: true
metric_func:
  _target_: torchxai.metrics.complexity.effective_complexity.effective_complexity
  _partial_: true
  feature_mask: null
  additional_forward_args: null
  target: null
  perturb_func:
    _target_: torchxai.metrics._utils.perturbation.default_random_perturb_func
    _partial_: false
    noise_scale: 0.02
  n_perturbations_per_feature: 10
  max_features_processed_per_batch: null
  eps: 1.0e-05
  ignored_indices: null
  return_ratio: false
  use_absolute_attributions: true
  is_multi_target: false
  show_progress: false
  return_intermediate_results: false
  return_dict: false
output_transform:
  path: insightx.metrics.torchxai_metric.default_output_transform
  _target_: hydra_zen.funcs.get_obj
device: cpu
progress_bar: null
attached_name: null
