_target_: insightx.metrics.torchxai_metric.TorchXAIMetric
_partial_: true
metric_func:
  _target_: torchxai.metrics.faithfulness.aopc.aopc
  _partial_: true
  feature_mask: null
  additional_forward_args: null
  target: null
  max_features_processed_per_batch: null
  total_features_perturbed: 100
  n_random_perms: 10
  seed: null
  is_multi_target: false
  show_progress: false
  return_dict: false
output_transform:
  path: insightx.metrics.torchxai_metric.default_output_transform
  _target_: hydra_zen.funcs.get_obj
device: cpu
progress_bar: null
attached_name: null
