_target_: insightx.engines.explanation_engine.ExplanationEngine
_partial_: true
defaults:
- _self_
- /engine_step@engine_step: default_explanation_step
- /explainer@explainer: grad/saliency
- /metric@metrics.completeness: axiomatic/completeness
tb_logger: null
epoch_length: null
outputs_to_running_avg: null
logging:
  _target_: atria._core.training.configs.logging_config.LoggingConfig
  logging_steps: 1
  refresh_rate: 1
  log_gpu_stats: false
  profile_time: false
  log_to_tb: true
metrics: null
metric_logging_prefix: null
test_run: false
is_single_output: true
