# @package __global__
_target_: hydra_zen.funcs.zen_processing
_zen_target: atria_insights.task_pipelines._explainer.Explainer
_zen_partial: false
_zen_exclude:
- pipeline_name
- n_devices
- backend
- experiment_name
defaults:
- /engine@test_engine: default_test_engine
- /engine@explanation_engine: default_explanation_engine
- /data_pipeline@data_pipeline: default
- /explainer_pipeline@explainer_pipeline: image_classification
- _self_
test_checkpoint: null
output_dir: outputs/explainer/image_classification/${resolve_experiment_name:${experiment_name}}/
do_eval: true
seed: 42
deterministic: true
pipeline_name: atria_explainer
n_devices: 1
backend: nccl
experiment_name: _to_be_resolved_
