# @package __global__
_target_: hydra_zen.funcs.zen_processing
_zen_target: atria_insights.task_pipelines._explainer.Explainer
_zen_partial: false
_zen_exclude:
- pipeline_name
- n_devices
- backend
- experiment_name
defaults:
- /engine@test_engine: default_test_engine
  /engine@explanation_engine: default_explanation_engine
- /data_pipeline@data_pipeline: default
- /model_pipeline@model_pipeline: layout_token_classification
- _self_
test_checkpoint: ???
explanation_engine: ???
output_dir: outputs/explainer/layout_token_classification/${resolve_experiment_name:${experiment_name}}/
do_eval: true
pipeline_name: atria_explainer
n_devices: 1
backend: nccl
experiment_name: _to_be_resolved_
