_partial_: false
metric_func:
  _target_: torchxai.metrics.faithfulness.faithfulness_corr.faithfulness_corr
  _partial_: true
  baselines: null
  feature_mask: null
  additional_forward_args: null
  target: null
  perturb_func:
    _target_: torchxai.metrics._utils.perturbation.default_fixed_baseline_perturb_func
    _partial_: false
  n_perturb_samples: 200
  max_examples_per_batch: 100
  frozen_features: null
  percent_features_perturbed: 0.4
  show_progress: true
  is_multi_target: false
  return_intermediate_results: false
  return_dict: false
output_transform:
  path: atria_insights.metrics.torchxai_metric.default_output_transform
  _target_: hydra_zen.funcs.get_obj
device: cpu
progress_bar: null
attached_name: null
module: atria_insights.metrics.torchxai_metric.TorchXAIMetric
_target_: atria_insights.registry.registry_groups.ExplainerMetricBuilder
