_partial_: false
metric_func:
  _target_: torchxai.metrics.faithfulness.infidelity.infidelity
  _partial_: true
  baselines: null
  additional_forward_args: null
  target: null
  feature_mask: null
  frozen_features: null
  perturb_func:
    _target_: torchxai.metrics._utils.perturbation.default_infidelity_perturb_fn
    _partial_: false
    noise_scale: 0.003
  n_perturb_samples: 10
  max_examples_per_batch: null
  normalize: true
  is_multi_target: false
  return_dict: false
output_transform:
  path: atria_insights.metrics.torchxai_metric.default_output_transform
  _target_: hydra_zen.funcs.get_obj
device: cpu
progress_bar: null
attached_name: null
module: atria_insights.metrics.torchxai_metric.TorchXAIMetric
_target_: atria_insights.registry.registry_groups.ExplainerMetricBuilder
