_partial_: false
metric_func:
  _target_: torchxai.metrics.faithfulness.sensitivity_n.sensitivity_n
  _partial_: true
  n_features_perturbed: 0.2
  feature_mask: null
  additional_forward_args: null
  target: null
  n_perturb_samples: 50
  max_examples_per_batch: 100
  frozen_features: null
  normalize: true
  is_multi_target: false
  return_dict: false
output_transform:
  path: atria_insights.metrics.torchxai_metric.default_output_transform
  _target_: hydra_zen.funcs.get_obj
device: cpu
progress_bar: null
attached_name: null
module: atria_insights.metrics.torchxai_metric.TorchXAIMetric
_target_: atria_insights.registry.registry_groups.ExplainerMetricBuilder
