_partial_: false
model: ???
is_multi_target: false
internal_batch_size: 64
grad_batch_size: 64
module: torchxai.explainers.random.RandomExplainer
_target_: atria_insights.registry.registry_groups.ExplainerBuilder
