_target_: atria_insights.explainer_pipelines.classification.image.ImageClassificationExplainerPipeline
_partial_: false
defaults:
- /model_pipeline@model_pipeline: image_classification
- /explainer@explainer: grad/saliency
- /explainer_metric@explainer_metrics.completeness: axiomatic/completeness
- /explainer_metric@explainer_metrics.input_invariance: axiomatic/input_invariance
- /explainer_metric@explainer_metrics.monotonicity_corr_and_non_sens: axiomatic/monotonicity_corr_and_non_sens
- /explainer_metric@explainer_metrics.complexity_entropy_feature_grouped: complexity/complexity_entropy_feature_grouped
- /explainer_metric@explainer_metrics.complexity_sundararajan_feature_grouped: complexity/complexity_sundararajan_feature_grouped
- /explainer_metric@explainer_metrics.effective_complexity: complexity/effective_complexity
- /explainer_metric@explainer_metrics.sparseness_feature_grouped: complexity/sparseness_feature_grouped
- /explainer_metric@explainer_metrics.aopc: faithfulness/aopc
- /explainer_metric@explainer_metrics.faithfulness_corr_2: faithfulness/faithfulness_corr_2
- /explainer_metric@explainer_metrics.faithfulness_corr_4: faithfulness/faithfulness_corr_4
- /explainer_metric@explainer_metrics.faithfulness_corr_6: faithfulness/faithfulness_corr_6
- /explainer_metric@explainer_metrics.faithfulness_estimate: faithfulness/faithfulness_estimate
- /explainer_metric@explainer_metrics.infidelity: faithfulness/infidelity
- /explainer_metric@explainer_metrics.monotonicity: faithfulness/monotonicity
- /explainer_metric@explainer_metrics.sensitivity_n_2_normalized: faithfulness/sensitivity_n_2_normalized
- /explainer_metric@explainer_metrics.sensitivity_n_4_normalized: faithfulness/sensitivity_n_4_normalized
- /explainer_metric@explainer_metrics.sensitivity_n_6_normalized: faithfulness/sensitivity_n_6_normalized
- /explainer_metric@explainer_metrics.sensitivity_max_and_avg: robustness/sensitivity_max_and_avg
- _self_
pipeline_name: image_classification
config_name: default
is_multi_target: false
segmentation_fn: grid
segmentation_fn_kwargs: {}
