_partial_: false
metric_func:
  _target_: torchxai.metrics.robustness.sensitivity.sensitivity_max_and_avg
  _partial_: true
  perturb_func:
    path: torchxai.metrics.robustness.utilities.default_perturb_func
    _target_: hydra_zen.funcs.get_obj
  perturb_radius: 0.02
  n_perturb_samples: 10
  norm_ord: fro
  max_examples_per_batch: null
  is_multi_target: false
  return_dict: false
output_transform:
  path: atria_insights.metrics.torchxai_metric.default_output_transform
  _target_: hydra_zen.funcs.get_obj
device: cpu
progress_bar: null
attached_name: null
module: atria_insights.metrics.torchxai_metric.TorchXAIMetric
_target_: atria_insights.registry.registry_groups.ExplMetricBuilder
