_partial_: false
is_multi_target: false
internal_batch_size: 64
grad_batch_size: 64
module: torchxai.explainers._grad.deeplift_shap.DeepLiftShapExplainer
_target_: atria_insights.registry.registry_groups.ExplainerBuilder
