_partial_: false
n_samples: 25
is_multi_target: false
internal_batch_size: 1
grad_batch_size: 64
module: torchxai.explainers._grad.gradient_shap.GradientShapExplainer
_target_: atria_insights.registry.registry_groups.ExplainerBuilder
