_partial_: false
is_multi_target: false
internal_batch_size: 50
n_steps: 50
grad_batch_size: 64
module: torchxai.explainers._grad.integrated_gradients.IntegratedGradientsExplainer
_target_: atria_insights.registry.registry_groups.ExplainerBuilder
