# @package __global__
defaults:
- /metric@explanation_engine.metrics.completeness: axiomatic/completeness
- /metric@explanation_engine.metrics.input_invariance: axiomatic/input_invariance
- /metric@explanation_engine.metrics.monotonicity_corr_and_non_sens: axiomatic/monotonicity_corr_and_non_sens
- _self_

explanation_engine:
  metrics:
    monotonicity_corr_and_non_sens:
      metric_func:
        perturb_func:
          _target_: torchxai.metrics._utils.perturbation.default_random_perturb_func
        n_perturbations_per_feature: 10
        max_features_processed_per_batch: 100
        eps: 1.0e-05
        show_progress: true